In [1]:
import numpy as np
from os import listdir
import fnmatch

from os.path import isfile, join, isdir
import pandas as pd

In [2]:
def get_rho(filename):
    for chunk in filename.replace(".csv", "").split("_"):
        if chunk.startswith('rho'):
            rho = float(chunk.replace("rho", ""))/10
    return(rho)

def get_p(filename):
    for chunk in filename.replace(".csv", "").split("_"):
        if chunk.startswith('p'):
            p = int(chunk.replace("p", ""))
    return(p)

def get_Delta(filename):
    for chunk in filename.replace(".csv", "").split("_"):
        if chunk.startswith('Delta'):
            Delta = int(chunk.replace("Delta", ""))
    return(Delta)

In [3]:
filelist=  [f for f in listdir("./result/") if fnmatch.fnmatch(f, '*.csv')]

Delta_list = []
p_list = []
rho_list = []
for fileitem in filelist:
    rho_list.append( get_rho(fileitem) )    
    Delta_list.append( get_Delta(fileitem))  
    p_list.append( get_p(fileitem))  
rho_list = np.unique( np.array(rho_list))
Delta_list = np.unique( np.array(Delta_list))
p_list = np.unique( np.array(p_list))

print(rho_list)
print(Delta_list)
print(p_list)

[0.5 4.5]
[3 4 5]
[ 80 160 240 320 400]


In [4]:



file_dict  = dict(zip(rho_list, [dict(
    zip(Delta_list, [dict(
        zip(p_list, ["" for p in p_list])
    ) for Delta in Delta_list])
) for rho in rho_list]))


for file_now  in filelist:
    rho_now =  get_rho(file_now)
    Delta_now =  get_Delta(file_now)
    p_now =  get_p(file_now)
    file_dict[rho_now][Delta_now][p_now] = file_now

In [5]:
experiment_name = "anisotropic_cov_oracle_new"
df_list = dict(
    zip(rho_list, [pd.DataFrame(columns=Delta_list, index =  p_list) for rho in rho_list])
    )


In [6]:

for rho in rho_list:
    rho_dict = file_dict[rho]
    for Delta in Delta_list:
        rho_Delta_dict = rho_dict[Delta]
        for p in p_list:
            file_name_now = './result/' + 'rho' + str(int(rho*10)) + '_Delta' + str(Delta)+ '_p' +str(p)  +'.csv'
            try:
                mean_now = pd.read_csv(file_name_now, header = None).to_numpy().mean()
            except:
                mean_now = 0
            df_list[rho].loc[p, Delta] = mean_now
    df_list[rho].to_csv("./"+ experiment_name + "_rho"+ str(rho) + ".csv" )


In [117]:
df_list[2]

0.2      0.5      0.8
5000    0.9927  0.98075   0.8844
6000   0.98835  0.97625   0.9062
7000    0.9885  0.97355  0.92015
8000   0.98345   0.9737  0.92955
9000   0.94965   0.9672      NaN
10000  0.93525   0.9637  0.93375

array([0.2, 0.5, 0.8])

In [ ]:
result = [i for i in some_list if i.startswith('GFS01_')]

In [25]:
table_now = np.zeros[()]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:

path_del5 = './del' + '/result/'

In [43]:
path_del5 = './del' + '/result/'
filelist_lapu_ell2 = [f for f in listdir(path_lapu_ell2) if isfile(join(path_lapu_ell2, f))]
filelist_lapu_ell2.sort()

path_genrr_ell2 = './'+'genrr_ell2' + '/result/'
filelist_genrr_ell2= [f for f in listdir(path_genrr_ell2) if isfile(join(path_genrr_ell2, f))]
filelist_genrr_ell2.sort()

path_bitflip_ell2 = './'+'bitflip_ell2' + '/result/'
filelist_bitflip_ell2 = [f for f in listdir(path_bitflip_ell2) if isfile(join(path_bitflip_ell2, f))]
filelist_bitflip_ell2.sort()


In [44]:
filelist_bitflip_ell2

['pval_k_2000_priv_20_bitflip_ell2_n_100000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_120000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_150000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_170000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_200000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_220000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_250000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_270000.npy',
 'pval_k_2000_priv_20_bitflip_ell2_n_300000.npy']

In [45]:
path_lapu_ell2 = './'+'lapu_ell2' + '/result/'
filelist_lapu_ell2 = [f for f in listdir(path_lapu_ell2) if isfile(join(path_lapu_ell2, f))]
onlyfiles.sort()

sample_size_list = np.array([10, 12, 15, 17, 20, 22, 25, 27, 30])
k2000_priv20_table = np.zeros([len(sample_size_list),4])

In [46]:
for i in range(len(sample_size_list)):
    print(i)
    k2000_priv20_table[i,0] = sample_size_list[i]
    k2000_priv20_table[i,1] = (np.load(path_lapu_ell2+filelist_lapu_ell2[i])<0.05).mean()
    k2000_priv20_table[i,2] = (np.load(path_genrr_ell2+filelist_genrr_ell2[i])<0.05).mean()
    k2000_priv20_table[i,3] = (np.load(path_bitflip_ell2+filelist_bitflip_ell2[i])<0.05).mean()

0
1
2
3
4
5
6
7
8


In [47]:
np.savetxt('k2000_priv20_mix.csv', k2000_priv20_table, delimiter = ',', header = "n, lapu, genrr, bitflip", comments = "")


In [ ]:
C:\Users\Jongmin\Documents\GitHub\LDPUts\simul\power\gaboardi\k_2000\priv_20\lapu_ell2\result\ lapu_ell2_n_100000.npy